name: CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI.yml
      - src/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI.yml
      - src/**

jobs:
  build-windows:
    runs-on: self-hosted
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Generate VS solution
      working-directory: src
      run: |
        reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v DefaultProjectExtension /t REG_SZ /d vcproj /f
        .\devtools\bin\vpc.exe /csso  /define:WORKSHOP_IMPORT_DISABLE /define:SIXENSE_DISABLE /define:NO_X360_XDK /define:RAD_TELEMETRY_DISABLED /define:DISABLE_ETW +appframework +datacache +datamodel +dedicated +inputsystem +gamedlls +engine +mathlib +tier0 +tier1 +tier2 +tier3 +vstdlib +particles +studiomdl +hlmv +vbsp +vvis_dll +vrad_dll +raytrace +studiorender +filesystem_stdio +materialsystem +shaderapidx9 +shaderapiempty +stdshader_dbg +stdshader_dx6 +stdshader_dx7 +stdshader_dx8 +stdshader_dx9 +vguimatsurface +vgui_dll +vgui_surfacelib +vgui_controls +matsys_controls +video_services +video_quicktime +video_webm +launcher +sourcevr +vtf +pet +dme_controls +sfmobjects +toolutils +vmt +commedit +vtex_dll +vtex_launcher +vpk +hammer_dll +hammer_launcher +fgdlib +shaderlib /mksln csso.sln /nop4add /nofpo /f 
        gc .\sln_fix.txt | ac .\csso.sln
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild src\csso.sln /m /nologo /p:Configuration=Release /t:"Clean;Build" /v:m
    - name: Prepare artifacts
      id: prepare_artifacts
      run: |
        robocopy mp\game\bin          artifacts\bin\bin          /xf *.pdb /r:0 /w:0
        robocopy mp\game\csso\bin artifacts\bin\csso\bin /xf *.pdb /r:0 /w:0
        robocopy mp\game\bin          artifacts\pdb\bin              *.pdb /r:0 /w:0
        robocopy mp\game\csso\bin artifacts\pdb\csso\bin     *.pdb /r:0 /w:0
        If ($LastExitCode -le 7) { echo "LastExitCode = $LastExitCode";$LastExitCode = 0 }
        echo "::set-output name=short_commit_sha::$(git rev-parse --short HEAD)"
    - name: Upload bin artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bin_${{ runner.os }}-${{ steps.prepare_artifacts.outputs.short_commit_sha }}
        path: artifacts\bin
        if-no-files-found: error
    - name: Upload pdb artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pdb_${{ runner.os }}-${{ steps.prepare_artifacts.outputs.short_commit_sha }}
        path: artifacts\pdb
        if-no-files-found: error
